name: Deploy Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Dev Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@rezurrection.website "cd /var/www/dev.rezurrection.website && git pull origin dev"
